# Deploys to prod on each push to the `main` branch.

name: Deploy to prod

on:
  push:
    branches:    
      - main

jobs:

  deploy-to-us:
    runs-on: ubuntu-18.04
    name: Deploy to Production
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: production
      - name: Running deployment
        run: |
          echo Deploying to Produktion ...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

  deploy-to-germany:
    runs-on: ubuntu-18.04
    name: Deploy to Produktion
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: Produktion
      - name: Running deployment
        run: |
          echo Deploying to Produktion ...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        
  deploy-to-brazil:
    runs-on: ubuntu-18.04
    name: Deploy to produção
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: produção
      - name: Running deployment
        run: |
          echo Deploying to produção ...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          
  deploy-to-russia:
    runs-on: ubuntu-18.04
    name: Deploy to продакшн
    steps:
      - uses: chrnorm/deployment-action@releases/v1
        name: Create deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          environment: продакшн
      - name: Running deployment
        run: |
          echo Deploying to продакшн ...
      - uses: chrnorm/deployment-status@releases/v1
        name: Update deployment
        with:
          token: "${{ github.token }}"
          target_url: http://my-cool-app.com
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
